apiVersion: v1
kind: Secret
metadata:
  name: mongosecret
type: Opaque
data:
  username: bW9uZ29hZG1pbgo=
  password: c2VjcmV0Cg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      hostname: rvstore-orders-mongodb
      containers:
      - name: mongodb
        image: mongo:latest
        volumeMounts:
        - name: mongodb-storage 
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongosecret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongosecret
              key: password
        ports:
        - containerPort: 27017
      volumes:
        - name:  mongodb-storage
          emptyDir: {}
