kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-sim-deployment
  labels:
    name: order-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-sim
  template:
    metadata:
      labels:
        app: order-sim
    spec:
      containers:
      - name: order-sim
        image: vergeops/k8s-rvstore-order-simulator:1.0
        envFrom:
        - configMapRef:
            name: api-configmap
