kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-api-deployment
  labels:
    name: order-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: vergeops/k8s-rvstore-order-api:1.0
        envFrom:
        - configMapRef:
            name: api-configmap
        ports:
        - containerPort: 9002
