apiVersion: v1 
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: compose
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: product-api-deployment
  labels:
    name: product-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: product-api
        image: vergeops/k8s-rvstore-product-api:1.0
        envFrom:
        - configMapRef:
            name: api-configmap
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-api-deployment
  labels:
    name: order-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: vergeops/k8s-rvstore-order-api:1.0
        envFrom:
        - configMapRef:
            name: api-configmap
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-sim-deployment
  labels:
    name: order-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-sim
  template:
    metadata:
      labels:
        app: order-sim
    spec:
      containers:
      - name: order-sim
        image: vergeops/k8s-rvstore-order-simulator:1.0
        envFrom:
        - configMapRef:
            name: api-configmap
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-gateway-deployment
  labels:
    name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: vergeops/k8s-rvstore-api-gateway:1.0
        envFrom:
        - configMapRef:
            name: order-api-configmap