kind: Deployment
apiVersion: apps/v1
metadata:
  name: product-api-deployment
  labels:
    name: product-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: product-api
        image: vergeops/k8s-rvstore-product-api:1.0
        envFrom:
        - configMapRef:
            name: api-configmap
        ports:
        - containerPort: 9001
