apiVersion: v1 
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: compose
---
apiVersion: v1
kind: Secret
metadata:
  name: mongosecret
type: Opaque
data:
  username: bW9uZ29hZG1pbgo=
  password: c2VjcmV0Cg==