kind: Deployment
apiVersion: apps/v1
metadata:
  name: ui-deployment
  labels:
    name: ui
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui 
    spec:
      containers:
      - name: ui
        image: vergeops/k8s-rvstore-ui:1.0
        livenessProbe:
          httpGet:
            path: / 
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
---
kind: Service
apiVersion: v1
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
  type: NodePort


